from migration.utils.functions import add_custom_field, create_doctype, add_permission, insert_data
from loguru import logger


add_custom_field('Supplier', 'supplier_code', 'Data')
add_custom_field('Supplier', 'is_customer', 'Check')
add_custom_field('Supplier', 'is_supplier', 'Check')
add_custom_field('Supplier', 'name_alias', 'Data')
add_custom_field('Supplier', 'address', 'Data')
add_custom_field('Supplier', 'contact_person', 'Data')
add_custom_field('Supplier', 'employee', 'Link', link_to='Employee')
add_custom_field('Supplier', 'supplier_group_1', 'Link', link_to='Supplier Group')
add_custom_field('Supplier', 'supplier_group_2', 'Link', link_to='Supplier Group')
add_custom_field('Supplier', 'supplier_group_3', 'Link', link_to='Supplier Group')
add_custom_field('Supplier', 'region', 'Data')
add_custom_field('Supplier', 'phone_number', 'Data')
add_custom_field('Supplier', 'fax_number', 'Data')
add_custom_field('Supplier', 'email', 'Data')
add_custom_field('Supplier', 'note', 'Data')
add_custom_field('Supplier', 'date_of_birth', 'Date')
add_custom_field('Supplier', 'legal_representative', 'Data')
add_custom_field('Supplier', 'position', 'Data')
add_custom_field('Supplier', 'bank_account_number', 'Data')
add_custom_field('Supplier', 'bank_name', 'Data')
add_custom_field('Supplier', 'bank_branch', 'Data')
add_custom_field('Supplier', 'bank_province_city', 'Data')
add_custom_field('Supplier', 'shipping_address', 'Data')
add_custom_field('Supplier', 'use_e_invoice', 'Select', options='Yes\nNo')
add_custom_field('Supplier', 'e_invoice_email', 'Data')
add_custom_field('Supplier', 'e_invoice_representative', 'Data')
add_custom_field('Supplier', 'order_source_table', 'Table', options='Order Source')
